baseURL = "https://romue404.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Robert MÃ¼ller"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

publishDir = "docs"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true